#!/bin/sh
# postinst script for cool-retro-term

set -e

case "$1" in
    configure)
    update-alternatives --install /usr/bin/x-terminal-emulator x-terminal-emulator /usr/bin/cool-retro-term 40
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
